---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-services
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/external-services
  prune: true
  wait: true
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: pb-backend
      namespace: external-services
