---
# Layer 1: Namespaces (must be first)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/namespaces
  prune: true
  wait: true
---
# Layer 2: Ingress Controller (after namespaces)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/ingress-nginx
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: ingress-nginx-controller
      namespace: ingress-nginx
---
# Layer 2: Cert-Manager (after namespaces)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cert-manager
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
---
# Layer 2: Reflector (secret/configmap replication)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/reflector
  prune: true
  wait: true
---
# Layer 2: External Secrets Operator (for dynamic namespace secret replication)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/external-secrets
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets-webhook
      namespace: external-secrets
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets-cert-controller
      namespace: external-secrets
---
# Layer 2: Nodepool RBAC (after namespaces)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodepool-rbac
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/nodepool-rbac
  prune: true
  wait: true
---
# Layer 3: Cert-Manager Configuration (after cert-manager is ready)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cert-manager-config
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Layer 3: Shared Certificates (after cert-manager is ready)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cert-manager
    - name: cert-manager-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/certificates
  prune: true
  wait: true
---
# Layer 3: ZooKeeper (after namespaces)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zookeeper
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/zookeeper
  prune: true
  wait: true
---
# Layer 3: PostgreSQL Database (after namespaces)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/database
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Layer 3: MinIO Object Storage (after namespaces, ingress, cert-manager)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: namespaces
    - name: ingress-nginx
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/minio
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
