apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system/
  - infrastructure.yaml
  - external-services.yaml
  - matrix.yaml
  - test-nginx.yaml
  - zuul.yaml
  - litellm.yaml
