---
# LiteLLM Proxy Server Application
# Depends on: zuul (same namespace)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 10m
  dependsOn:
    - name: zuul
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/litellm
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age