---
# ClusterExternalSecret to replicate zuul-executor-pubkey to nodepool namespaces
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: zuul-executor-pubkey
spec:
  # Name of ExternalSecret created in each namespace
  externalSecretName: zuul-executor-pubkey

  # Target namespaces with nodepool labels
  namespaceSelectors:
    - matchLabels:
        nodepool_provider_name: kubernetes-pods

  # Reconcile every minute to detect new namespaces quickly
  refreshTime: "1m"

  # ExternalSecret template
  externalSecretSpec:
    # Use the ClusterSecretStore we created
    secretStoreRef:
      name: zuul-kubernetes-store
      kind: ClusterSecretStore

    # Refresh the secret every 5 minutes
    refreshInterval: "5m"

    # Target secret configuration
    target:
      name: zuul-executor-pubkey
      creationPolicy: Owner

    # Data to sync from source secret
    data:
      - secretKey: pubkey
        remoteRef:
          key: zuul-executor-pubkey
          property: pubkey
