apiVersion: operator.zuul-ci.org/v1alpha2
kind: Zuul
metadata:
  name: zuul
  namespace: zuul-system
spec:
  # Image configuration
  imagePrefix: quay.io/zuul-ci/
  imageTag: latest

  # External database
  database:
    secretName: zuul-db-uri
    key: dburi

  # External ZooKeeper
  zookeeper:
    hosts: zookeeper.zookeeper-system.svc.cluster.local:2181

  # Scheduler - single replica for homelab
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

  # Web UI - single replica
  web:
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    service:
      type: ClusterIP
      port: 9000

  # Executor - single replica
  executor:
    replicas: 1
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    # Talos: Use allowed volume path
    volumeMounts:
      - name: workspace
        mountPath: /var/lib/zuul
    volumes:
      - name: workspace
        emptyDir:
          sizeLimit: 10Gi

  # Merger - single replica
  merger:
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  # Nodepool launcher
  launcher:
    config:
      secretName: nodepool-config
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  # Source code connections
  connections:
    - name: github
      driver: github
      secretName: github-connection

  # Tenant configuration
  tenants:
    secretName: zuul-tenant-config
