apiVersion: operator.zuul-ci.org/v1alpha2
kind: Zuul
metadata:
  name: zuul
  namespace: zuul-system
spec:
  # Image configuration
  imagePrefix: quay.io/zuul-ci

  # External database
  database:
    secretName: zuul-db-uri

  # External ZooKeeper with TLS
  zookeeper:
    hosts: zookeeper.zookeeper-system.svc.cluster.local:2281
    secretName: zookeeper-client-tls

  # Scheduler - single replica for homelab
  scheduler:
    count: 1
    config:
      secretName: zuul-tenant-config

  # Web UI - single replica
  web:
    count: 1

  # Executor - single replica
  executor:
    count: 1

  # Merger - single replica
  merger:
    count: 1

  # Nodepool launcher
  launcher:
    config:
      secretName: nodepool-config

  # Source code connections
  connections:
    gerrithub:
      driver: gerrit
      server: review.opendev.org
    github:
      driver: github
      app_id: "000000"
      app_key: /etc/zuul/github_rsa
      webhook_token: PLACEHOLDER
