apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pb
  namespace: external-services
  annotations:
    # Enable automatic HTTPS redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # Backend uses HTTPS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    # Skip TLS verification for self-signed backend certificate
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"

    # Supported TLS protocols for backend
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.2 TLSv1.3"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pb.teim.app
      # Uses wildcard certificate
      secretName: teim-app-wildcard-tls
  rules:
    - host: pb.teim.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pb-backend
                port:
                  number: 443
