creation_rules:
  # Encrypt secrets in apps/zuul/secrets/
  - path_regex: apps/zuul/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData|literals)$
    age: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t

  # Encrypt database secrets and kustomization
  - path_regex: infrastructure/database/.*\.yaml$
    encrypted_regex: ^(data|stringData|literals)$
    age: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t

  # Encrypt any file with .enc.yaml extension
  - path_regex: .*\.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
