apiVersion: v1
kind: Namespace
metadata:
  name: matrix-system
  labels:
    app.kubernetes.io/name: matrix
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
