apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper-system
  labels:
    app.kubernetes.io/name: zookeeper
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
