apiVersion: v1
kind: Secret
metadata:
    name: litellm-keys
    namespace: zuul-system
    labels:
        app.kubernetes.io/name: litellm
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: zuul-homelab
type: Opaque
data:
    #ENC[AES256_GCM,data:EPFVmIrCwRxZJvPBa74R7dVC5nb1UYKUltL5OSf5GsDllPvU/yqV88q8LoKT7eLyveQ=,iv:LHnjbQOOeh0wXDzoVIuErdF52CvSBz/lICpXN4tgZRk=,tag:ISOfdLGngU+9G2NBzkZVIw==,type:comment]
    Z_AI_API_KEY: ENC[AES256_GCM,data:5r3MgYXVZ5xTTbs7S3+cCD3IdgN3l0FCd8XnVxLnqbSgo6mrRfMEkahhhqguT3rZjWUSRR7RDv+LE9gI8FXAXPTOZoM=,iv:0yIqpXyw93rOHA7g3w/5tuXU+9QLu6RIo7F8kpx7UDw=,tag:14KWaHnx0o4FoRQhQQFvNA==,type:str]
    #ENC[AES256_GCM,data:XPCBKljLA2+aNoADd7MexPMQ,iv:0nm1ABjCjNfAfMRGUnQJlAE3MwxfP1LVRdBWNZFFBDg=,tag:pHk9z4ujk3kepOsRWvpD5Q==,type:comment]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:NECgAUyHcXX5bq0V,iv:tJEmth3OHYGv7gRTBlh8fJRCZOISFMfxWLYwstiYvy8=,tag:VD50Ly390eZpfEApBHqlWA==,type:str]
    #ENC[AES256_GCM,data:kUtEeXRxkjfyPnmMOIvVzqLBiqr6VsICTIBc,iv:u0twDwuAH922r3OZNXB0ydbejA11IXL8/iKuX+xpPzk=,tag:otWUXJ/cjSPhWqqmpH9kUw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:H2DysUc8tJYBdLST9wh0sR9RXV+WC1eL8MwKgY2zmSJzC8E1NitVkibhXfgRAD8uzjAF4hgTgHPklRGh,iv:Rn0UUaEpEQpRkcoyDQCfHR+dhwnHieHLH/GAZAy/6hE=,tag:b/nFLei6OXHnz3a0nZNVLw==,type:str]
    #ENC[AES256_GCM,data:6HvLcUzFjdW/OeIZ/gdD1XJjXxlB,iv:1meXBzzOW4M/yf+2Oc5K5L62Yqkj8UpeqzqsBpFSPXs=,tag:AIF4/nS9wTV90dfTGswtRw==,type:comment]
    REDIS_HOST: ENC[AES256_GCM,data:vPsX9zqDoJSt5mb4/9IUWA==,iv:Zqg1TGQc4fcQUwC3kWxUz5r7SdxdJac9r5qH1BrnIzg=,tag:8a5jbyTqAAdonxKlE4c52Q==,type:str]
    #ENC[AES256_GCM,data:2pafcIP0sWS/dxIx7eQA,iv:5E+6F7CgwLALYP/uL7piCartr//GkpcnQGy8ehzN2T8=,tag:iR19Xf6u6vd91zo3iNh1dg==,type:comment]
    REDIS_PORT: ENC[AES256_GCM,data:Z0a+zDMSFb8=,iv:XULg9sECAbcgSgz7N0jgU8svWl0Bq7ovNcmI/gph//M=,tag:2aqRwTeCVqOLTiRa4FS0Bg==,type:str]
    #ENC[AES256_GCM,data:cBHMTj6sLr++knYeAIVykD6B+nBl93dr5w==,iv:1bPDqnzbMZFt//f5n7iRKBhZUmaouEUxyTRsvz7EZS4=,tag:lauUp2gXSdDliAUspes/Gg==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:gsJuiADHWeugbGk3qA0JMNH45yw=,iv:19Lx6Wmnl2fM1xC2blqBd6k5HoNGRFmT3QxNqfLAIP4=,tag:wVWSFR34aIH0Os1uU1gZhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcWlKcVFYNFc0TUhSbms2
            U1lCc2FrdndieXB2TW1lc2VkN2MvQkxsbEVvCklmVUhsdWhsdDZZWVhSRklsMHI0
            Y1Btek1XU1J3aG5jbk16dms1ay9TRmMKLS0tIDZzdWtIVzZCNmZTU2E2eVhiQ2lW
            dW80WGtuVTBMMWVPRjZMU3JkVnVGS1EKhNJPs3KJ56AereXmr0UGdIUINQp9e9ee
            up4zt9IzgbQT2ml7a16s/uuqIp2gOp5/JOwZS4gILR+nhuG8Nc3f3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T01:37:59Z"
    mac: ENC[AES256_GCM,data:OHcKmyTvIgpgT2cD79ai76w2+hjhNKsN0Qcwkfg/zJE/uCVi9dIfPde3k2FqQzuHuGaI9H7vEJxmEs+Od7aDrmVcGwuIuyC1bPAI/2Z1ZrfcD/3Zpbe8IjSmGkgZ9n/vBmZSWBur/oePGULUqZNiRIUwNBPxn1SS0HesHXY9Y3U=,iv:iKsz99EAbwYS73aN6SIvzty6IW2Z3YJF6HUF9Lk6WuY=,tag:ywQjGca6n2JaTStIBHio8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|literals)$
    version: 3.8.1
