apiVersion: v1
kind: Secret
metadata:
    name: litellm-keys
    namespace: zuul-system
    labels:
        app.kubernetes.io/name: litellm
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: zuul-homelab
type: Opaque
data:
    #ENC[AES256_GCM,data:f8GmD7lbras16bsyPnlOia0iVDV6dWDGzcK7Ob5/XB5GFbJV7M9g0g1sMSsqgDUcD9w=,iv:G0GrJvUDAqSgB2Ydnilk2W9A0B+87Sz+nlpOT0MwI8E=,tag:ouU0TqWTbHSOS75BCN0Kbw==,type:comment]
    ZAI_API_KEY: ENC[AES256_GCM,data:jgsyghKtNSk3X63bOXgQZLH5yJ6fUJZUGoECJTOLCKBPXyRw3Jnx1pCt0T7TKvL3y2b4hG9nq/ymdjC0Qi1MikITXEc=,iv:frFBXZblp3e7eTeqO9B1wklFfNr934vK77AoHoR32kY=,tag:14+MV1gzTdjpBtFDnqlIXA==,type:str]
    #ENC[AES256_GCM,data:l/XlMlcpweEkoQhJ1E0ce1gu,iv:Ux5DnGsHE1mRBR9UrHHfGn51Zlk9QneuDPTzFxd/d5k=,tag:t8Dn17DBBw7x9yVBeTP/0g==,type:comment]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:TWdwMTiOaJQV/0Uw,iv:Fo1NqiSJpWnkNrZYSaZSY+Y1AghQ/udlnhOd3vTgZGQ=,tag:on563wMmGN0AzZUYAtxvdw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FHS7X1qTV9xrIgEFTfNKXgbNqTVhAY/0pYyOF5p8yPO3F4lrngcNaDHp2G6VxIywYNqGFSn5ztzBoKPc4YoVjS4YgXuulRLatnjQD1SfEX4tOaDjgb5J/ekEXciVXkiRe3EFDO2u8yBupKElUMWzr+t1HS70LIwI5+O/qcnnIat73dF2,iv:+vBpFEcikarlKVcT8uKBHl2gCPq7NW1BCfVELcMb7vM=,tag:l+evz/uwCjGGnJtdW4Bm/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cjBqM296WXFJM1JhNGNn
            QVJ3ejQ5RjBDNWdFUDNIZVVtVlNkc0UzYTJjCktJM2lyV1RNUE9TRjZFMTNsOWVt
            czNxZ1ZlS25iM1RuL0FKMk1iRnBRUFkKLS0tIDZTS3Jndi96S1dWWmV0aFJUZ2pQ
            b3BNTGtkcXdoeHdWMFlxRjVVQm50NFEKFlSnT4dNXDLZcpDFIKlhpqsVVP7Uh2gj
            bIIZMUAV222s5oplKvFcq4qYECXHJWePWkXRxZ7jNuZfn/SbLKqgWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T23:09:52Z"
    mac: ENC[AES256_GCM,data:ixi/Nof+jgZKoD4q/q6fjAgjkKxZIHpYD8EsBBXGil2tz7sHK6sU1BdrN6MtPPw5BMNyvJOmUJeFm8L1jKCr9DZ2qRmBNdyYAxCU2RZb6EhRp+swR9RszT+E3kjb357YVERftqU+dk9SuxJUHyLtC1kuDzmP04a1LosY6dXJMSk=,iv:voSXh9xqtL3BaHUVGBBrU/iouy84CSp6TqHck/1LdHY=,tag:8WqzcBdzgnJUisI/cHr6Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
