---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# Let's Encrypt Staging - use for testing to avoid rate limits
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sean@seanmooney.info
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      # DNS-01 challenge using Cloudflare for wildcard certificates
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
        selector:
          dnsZones:
            - 'teim.app'
---
# Let's Encrypt Production - use after testing with staging
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sean@seanmooney.info
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      # DNS-01 challenge using Cloudflare for wildcard certificates
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
        selector:
          dnsZones:
            - 'teim.app'
