---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul-system

resources:
- statefulset.yaml
- service.yaml
- configmap.yaml
- secrets/

# Common labels - only apply to metadata, not to selectors
labels:
- pairs:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: zuul-homelab