---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: zuul-system
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: zuul-homelab
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: proxy