---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litellm
  namespace: zuul-system
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: zuul-homelab
spec:
  serviceName: litellm
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litellm
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: zuul-homelab
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-stable
        imagePullPolicy: IfNotPresent
        args:
        - "--config"
        - "/app/config.yaml"
        - "--port"
        - "4000"
        - "--num_workers"
        - "2"
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: litellm-keys
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health/liveliness
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config