---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litellm
  namespace: zuul-system
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: zuul-homelab
spec:
  serviceName: litellm
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litellm
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: zuul-homelab
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-stable
        imagePullPolicy: IfNotPresent
        args:
        - "--config"
        - "/app/config.yaml"
        - "--port"
        - "4000"
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: litellm-keys
        env:
        - name: HOME
          value: "/tmp"
        - name: XDG_CACHE_HOME
          value: "/tmp"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DATABASE_URL
          value: "postgresql://litellm:litellm_password_123@postgres.postgres-system.svc.cluster.local:5432/litellm"
        - name: PRISMA_BINARY_PATH
          value: "/tmp/.prisma"
        - name: PRISMA_CACHE_DIR
          value: "/tmp/.prisma-cache"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        - name: cache-volume
          mountPath: /tmp
        - name: root-cache-volume
          mountPath: /.cache
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health/liveliness
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config
      - name: cache-volume
        emptyDir: {}
      - name: root-cache-volume
        emptyDir: {}
