apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul-system

secretGenerator:
  - name: zuul-tenant-config
    files:
      - main.yaml=tenant-config.yaml
    options:
      disableNameSuffixHash: true

  - name: nodepool-config
    files:
      - nodepool.yaml=nodepool-config.yaml
    options:
      disableNameSuffixHash: true
