zookeeper-servers:
  - host: zookeeper.zookeeper-system.svc.cluster.local
    port: 2281  # TLS-enabled port

labels:
  - name: ubuntu-24-04-pod
    min-ready: 0
  - name: debian-13-pod
    min-ready: 0
  - name: debian-claude-code
    min-ready: 0
  - name: almalinux-10-static
    min-ready: 0
  - name: centos-10-stream-static
    min-ready: 0

providers:
  - name: kubernetes-pods
    driver: kubernetes
    max-servers: 8
    pools:
      - name: main
        labels:
          - name: ubuntu-24-04-pod
            type: pod
            python-path: /usr/bin/python3
            cpu: 2
            memory: 2048
            spec:
              containers:
                - name: ubuntu-24-04-pod
                  image: ghcr.io/seanmooney/ci-test-node-ubuntu-24.04:latest
                  imagePullPolicy: Always
                  env:
                    - name: SSH_AUTHORIZED_KEYS
                      valueFrom:
                        secretKeyRef:
                          name: zuul-executor-pubkey
                          key: pubkey
          - name: debian-13-pod
            type: pod
            python-path: /usr/bin/python3
            cpu: 2
            memory: 2048
            spec:
              containers:
                - name: debian-13-pod
                  image: ghcr.io/seanmooney/ci-test-node-debian-13:latest
                  imagePullPolicy: Always
                  env:
                    - name: SSH_AUTHORIZED_KEYS
                      valueFrom:
                        secretKeyRef:
                          name: zuul-executor-pubkey
                          key: pubkey
          - name: debian-claude-code
            type: pod
            python-path: /usr/bin/python3
            cpu: 2
            memory: 2048
            spec:
              containers:
                - name: debian-claude-code
                  image: ghcr.io/seanmooney/ci-node-claude-code:latest
                  imagePullPolicy: Always
                  env:
                    - name: SSH_AUTHORIZED_KEYS
                      valueFrom:
                        secretKeyRef:
                          name: zuul-executor-pubkey
                          key: pubkey
  - name: static-alma
    driver: static
    pools:
      - name: main
        nodes:
          - name: 192.168.17.30
            labels: almalinux-10-static
            host-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG4aLqWl7zJUVM9ZssxONDJAhK0LdfTNmBnh280K+lLR"
            username: alma
            python-path: /usr/bin/python3
            max-parallel-jobs: 1
  - name: static-centos-10-stream
    driver: static
    pools:
      - name: main
        nodes:
          - name: 192.168.17.173
            labels: centos-10-stream-static
            host-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ4Icxzjrzp6JpwvrQrrbKnXxIC6L7Kk03UaeoE1vqL5"
            username: zuul
            python-path: /usr/bin/python3
            max-parallel-jobs: 1
