apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: zookeeper-system
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  clusterIP: None
