apiVersion: v1
kind: Secret
metadata:
    name: executor-sshkey
    namespace: zuul-system
type: Opaque
stringData:
    sshkey: ENC[AES256_GCM,data:Aufe8WJLWiBg2IrN6t5MOhdI3cvoFvODloJqlvZTtfroFY1D2JDKBsIra9insshejga81OhNl6p4IGXUdORHefqFM93Z9YngBwF4epVYuBEQ5IhbzitYiAfUPTxGfv/gn8OTWKuIW84pTrcvAKz/AugN5nZFjZ1MyClwWz3x8pbFnJgmjzKdC/jSK7myoPO3cJ0jq4EoZqutnGyzrvFu7VwF4YxAbfvIviudc2w4BiT12FWb0vsqr0s1aIf8wb11aLAsmKrVr3H56dvFyG7gjkIp7LEbTJsTvDvrs+ls26UD7K8BPaKWgpwT6Af+NMA8VGLyvvEl7IX/SNNO2UMpJtF0SZfS5626s8dKpnK5xWVB5n+cRpJItR1HNwz0g7v6Iij4E0jRWb4W9WWG7hdC0RtLfCTQdS4bNvnm8EH3iESMyGiptkNWV+kCdjRz63OUluaMkmPlhyuAGCLOOJUlUlbmq2ejYgva7NujC7WLIHIh89Q3c+ROfcQUaLGtS92FbcRAeEzcRVVHsc9jiBEVU5CSYJ+zAXuR4ES00tEWz+OqhSg=,iv:9dVX7cceygPuaS69w371PPh0jW3d6DDri/xPj0kx9J0=,tag:oD59Cd91jj3EFFE5dSCh/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MUFubmtldkpGZzBpYTE4
            bktHa1VucW13TnY3bC92MXJLbFZWdVF5TUZnCmEydVVGdkNGWkdDYmZ6dWJQUUFU
            SHlNWHJCZnFhZzJuNW16TlZoV0xQaUEKLS0tIE45bHdjRFZRelc1Z2VxU21GOHV3
            NFJBTDQrUnlWcUhRK2FHTjU1SFdOUGsKtVbqEFXWtIy4t7RPYlLN0VuY6dZKNhQH
            ztoyINhRMJ+QwzzlZpMFEGAzQ8C3E+rpqqzc0bW3uESCShFTeKyH+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T16:08:21Z"
    mac: ENC[AES256_GCM,data:NwlmYkMfsI3HMMi5e/hoYLDj86BHGO5c1xTtCELV2K5/YzLFYZCYTUAk5z9SDxHMXmFfQpYCG+tK2BNPUiEWie5qZwZzLxGfoXIpUoRjxNLhXCL6tVGL1PctyFWe0feoXPqIWq1vC1Mqq702eRGJ3sMkRJcKNGQgNBp78vnOliE=,iv:U49/QxlP+w4f7MWG4Wp5Lfd0GPdY5ema2EokyphnF2M=,tag:A8y9335OEVa9VgTFwgUyCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|literals)$
    version: 3.8.1
