apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul-system

resources:
  - github-connection.enc.yaml
  - db-uri-secret.enc.yaml
  - gerrit-connection.enc.yaml
  - minio-logs-secret.enc.yaml
  - executor-sshkey.enc.yaml
