apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-operator
  namespace: zuul-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zuul-operator
  template:
    metadata:
      labels:
        name: zuul-operator
    spec:
      serviceAccountName: zuul-operator
      containers:
        - name: zuul-operator
          image: quay.io/zuul-ci/zuul-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: zuul-system
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: zuul-operator
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
