apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zuul-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets", "namespaces"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["*"]
  - apiGroups: ["operator.zuul-ci.org"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zuul-operator
subjects:
  - kind: ServiceAccount
    name: zuul-operator
    namespace: zuul-system
roleRef:
  kind: ClusterRole
  name: zuul-operator
  apiGroup: rbac.authorization.k8s.io
