apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zuul-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "services/finalizers", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets", "ingresses", "namespaces"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments/finalizers"]
    resourceNames: ["zuul-operator"]
    verbs: ["update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["*"]
  - apiGroups: ["operator.zuul-ci.org"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["issuers", "certificates", "certificaterequests"]
    verbs: ["*"]
  - apiGroups: ["pxc.percona.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zuul-operator
subjects:
  - kind: ServiceAccount
    name: zuul-operator
    namespace: zuul-system
roleRef:
  kind: ClusterRole
  name: zuul-operator
  apiGroup: rbac.authorization.k8s.io
