apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: test-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>FluxCD Test - Nginx</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
            }
            .container {
                background: white;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            h1 {
                color: #0066cc;
                border-bottom: 3px solid #0066cc;
                padding-bottom: 10px;
            }
            .status {
                background: #d4edda;
                border: 1px solid #c3e6cb;
                color: #155724;
                padding: 15px;
                border-radius: 4px;
                margin: 20px 0;
            }
            .info {
                background: #e7f3ff;
                border-left: 4px solid #0066cc;
                padding: 15px;
                margin: 20px 0;
            }
            code {
                background: #f8f9fa;
                padding: 2px 6px;
                border-radius: 3px;
                font-family: monospace;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>FluxCD + Talos Kubernetes</h1>

            <div class="status">
                <strong>✓ Status:</strong> FluxCD GitOps is working!
            </div>

            <div class="info">
                <h2>Deployment Details</h2>
                <ul>
                    <li><strong>Application:</strong> Nginx Test Webserver</li>
                    <li><strong>Domain:</strong> nginx.teim.app</li>
                    <li><strong>TLS Certificate:</strong> Let's Encrypt (DNS-01 Challenge)</li>
                    <li><strong>DNS Provider:</strong> Cloudflare</li>
                    <li><strong>Namespace:</strong> test-nginx</li>
                    <li><strong>Managed by:</strong> FluxCD GitOps</li>
                    <li><strong>Platform:</strong> Talos Kubernetes</li>
                    <li><strong>Repository:</strong> github.com/SeanMooney/zuul-homelab</li>
                </ul>
            </div>

            <div class="info">
                <h2>What's Next?</h2>
                <p>This test application validates that:</p>
                <ul>
                    <li>FluxCD is successfully monitoring the Git repository</li>
                    <li>Changes in Git are automatically applied to the cluster</li>
                    <li>The GitOps workflow is fully functional</li>
                </ul>
                <p>Try editing this page in <code>apps/test-nginx/configmap.yaml</code> and pushing to see automatic updates!</p>
            </div>
        </div>
    </body>
    </html>
