apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: test-nginx
  annotations:
    # Enable automatic HTTPS redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Note: Certificate is managed separately via Certificate resource
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nginx.teim.app
      # This secret is created by the Certificate resource
      secretName: teim-app-wildcard-tls
  rules:
    - host: nginx.teim.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
