apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: test-nginx
  annotations:
    # Enable automatic HTTPS redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Use Let's Encrypt staging for testing (switch to letsencrypt-prod when ready)
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nginx.teim.app
      secretName: nginx-teim-app-tls
  rules:
    - host: nginx.teim.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
