---
apiVersion: v1
kind: Service
metadata:
  name: opencode
  namespace: zuul-system
  labels:
    app: opencode
spec:
  type: ClusterIP
  ports:
  - port: 4096
    targetPort: 4096
    protocol: TCP
    name: http
  selector:
    app: opencode