---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opencode
  namespace: zuul-system
  labels:
    app: opencode
spec:
  serviceName: opencode
  replicas: 1
  selector:
    matchLabels:
      app: opencode
  template:
    metadata:
      labels:
        app: opencode
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: opencode
        image: ghcr.io/seanmooney/ci-test-node-debian-13:latest
        command:
        - /bin/bash
        - -c
        - |
          export PATH="/home/zuul/.opencode/bin:${PATH}"
          exec opencode serve --port 4096 --hostname 0.0.0.0
        ports:
        - containerPort: 4096
          name: http
          protocol: TCP
        env:
        - name: HOME
          value: /home/zuul
        volumeMounts:
        - name: auth-config
          mountPath: /home/zuul/.config/opencode/auth.json
          subPath: auth.json
          readOnly: true
        - name: workdir
          mountPath: /home/zuul
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /app
            port: 4096
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /app
            port: 4096
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: auth-config
        secret:
          secretName: opencode-auth-config
          items:
          - key: auth.json
            path: auth.json
      - name: workdir
        emptyDir: {}