apiVersion: v1
kind: Secret
metadata:
    name: synapse-secrets
    namespace: matrix-system
    labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/part-of: matrix
type: Opaque
stringData:
    homeserver-secrets.yaml: ENC[AES256_GCM,data:ctO7yVvRviC1IM+DgITP4nV7ZeBs/TtSS5Jlq+uF3AoPIOP9vhgQqm4ibg7ErYIXXqQpVCVhIXcIwZ88nqHUIpNhSZfom8NHxdIueMojFZIaQabaHQXBgouf3+vcJzMG3gXuXx/VUFc4mn8OdupVnwUMQuJJStlnAuO/STkaPkmvgU21tKgnreROuH7t5xgWzZW+cmVLrJB30pR59bkAiwO55AjLa9K/gDKJ4wXSqprl3SOaHtqLbOueHe5SSuZpfB4ulk++wnoz/y9TNzRTeBoqd7q537sBlgldxUrBudK8PFWQJWFuhPT+8kHQ6MsskSBTZs/crqg8JiG0T7eKH+n/32aScvK8b23ODNIKH2PJyRH90533iizAPEVf+AZwC+P3e+6AVlGVZWjyWXPUr1+J1Oh60Ns7A1Y6rXHdC4RMGhC6MZrlX0w6,iv:28AJWJu2MRwV3GWcFZLs5Acy7+X4X6onnK/ukT4x234=,tag:3jQgfDmEz/ABOBbliA7Bww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZHJLTkFwaUJIdEpPb1JP
            UDJERVhLVStOTTUwaERzU3E3azVzUXl6Y2xvCnNnQkRkWWM1MnowTU9XeUFOK1ZS
            eU1WcFRzRXRTTkdQdGUxWnc3UTRXMW8KLS0tIHdZcHVyTDJTYWRXU3JodDZ6NlM3
            empoRWJEVDdxY1JoNkswRWR4aGtjbm8KnWKyi9w5MiFwCFY2ZMXimZy6BXb9GhtQ
            4UPTb5WrsXdUQwrdtGv9uxbcSgXqOsW5FckNtsTcLImzqDycQd5l9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T10:36:05Z"
    mac: ENC[AES256_GCM,data:zzYjmJV9BPMelR7kmOj2yCkMjCb3i1fpI7Q0dfoN4rJbEgQfEtc50tf/iYgEKmNHJ6gn/iXw1hTCP1m9y0sRMEURKW4/7EK4Zv2JNF8FTC0F0GIgkql68SYucN8Rn0UYZAUSTD+bLusMwVE4Ig1uvgaHfyNkDAEdLdcg9dItFgU=,iv:5a29J9B3AP70BRePKdOOe5HhIyuJd63fQ8uWpJoZEH8=,tag:XeWEVREMHicqPtT1zWkdVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
