apiVersion: v1
kind: Secret
metadata:
    name: synapse-secrets
    namespace: matrix-system
    labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/part-of: matrix
type: Opaque
stringData:
    homeserver-secrets.yaml: ENC[AES256_GCM,data:OVobT8yXhTQ27X/y/GvzYFbs5OjyPYLPWgZs0p+BOVeM0l1tvJZ1seeuAUS7UYGQYlQdwLLDi/MolFV55UBbS/u03fGudctiit4IWfa614iWRBauCMZ0BqafC4l7jyepveRkRdXl2zKvoQULVeNNGy2tsC/dKhD7IKRYAh/lj+W/vp6tUHyHuM40jFlmNIp5o1TG92OxuIuPSJ0D0n/pdHaq5gEikDI1jPqowfdFyGW8KETpGVGAt9LccE9F4lLHzlJRgBK6YE8EHkns+/zQm2yd/2Yg7paiI+FVRBvcAsJFkCtfZ5chtSQJFSJGzla74K/cBB2H4MkuZBEmhb8JPaXo4mD438XcvBBC0GoVwtUq9mLouAAAdC5RfpoPwQeFBbBhuVsH9OSoQ4vrynjCk90QNkUDMPFcl9Yjnae7mojeb7lREn1N0FVYlkKrkwohZz84NVl8VV2WfWWVAfNds8KGHPZfSStZhzFRXx/hMrz5nC0Y7l+gGUgRRTbuU3usnO3yj17xxAsxRcn/M5/uGII2n5g3aTs8skozNWgnJfZ7JOx7546WGV7JcyYPn8rDhknZehvG3WH8OJCMyrMMFlxdIxYsp5DuhiDe7UKEffE2sZ29AmOVYX8M5Vz5ZToI+nGofw==,iv:88/XtzWE4dZpoMrYq06oHqBP/SHP6tsiTkZ39J1INDg=,tag:cJ+NtSgWj2Jr4r9f3dZMYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYVlZa3dhcUg1ME1yZytm
            QXpuUktLdEJLUGtZbFdGQ2l5YS9NZUJpM2dvCnQvMXhtZlJLMHZtbEJEUTBCR2xl
            TDF6OWRva2NNdWh3MzVlMHBIMlpWR0kKLS0tIGJwTDRPSWNBeElGM1RydGZWTnZI
            Vi9PRFkrcHJCWlcxV0dqWUF6MWxSTmcKkzu7ivnvz/B6Hh729uhOMpaAFJY7KNp9
            MnhBzaSS1CjRUW18ayCkgaOqPjX6WyU4oktLYF+TfZ6/xpnDlmM6YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T10:55:18Z"
    mac: ENC[AES256_GCM,data:7NyKPTSEgtS9YA8tjn+UmLL/N6aIv4wPcVK2h3Ct/wctQ15OqvIdr3HnAE/uZFeZjo6RNDLt+pZu04kGKQxGNgw7unljyV2RgRXqGa0dCARTSAR71UIJENwRy7nj8z7vhsHXt5JwwZevTWl5YCxkB6AfnApRxaeTkcsgPQZIuBM=,iv:dmQ3I9nck79wLC/DFWmOdOH3EMLTzfTUmh4O6V7Bmpo=,tag:uqJkp1jDde59ftc/x/6n6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
