apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matrix-system

resources:
  - pvc.yaml
  - synapse-statefulset.yaml
  - synapse-service.yaml
  - element-deployment.yaml
  - element-service.yaml
  - ingress.yaml
  - configs/
  - secrets/
