apiVersion: v1
kind: Secret
metadata:
    name: opencode-auth-config
    namespace: zuul-system
type: Opaque
stringData:
    auth.json: ENC[AES256_GCM,data:xAv2nwCX69W9+5qYzqAZ22/WQwPcJM/YYwCZbJ/4FRfSdtQiLVVL4YGpDTXK1kBg2norPp6q1B2LtCVrRJ5UnE8/YItGH0hL2OPOPmwlHkzDf5ZbBkcEtkrPZvoVHLBXvcMeOlJ6r4oCVfxIxju3Hw==,iv:yLPV9+3QVoSFSwcvvXQvMdp/HJrmtzbUreSDPmzaz5c=,tag:+n+M1LabBtDWNY8zobGwWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akle2yksua7txww5e86es4665pnmr875lpuax7rjvw0m7qthhq8s8fzm7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU1BHK3hPaHZVT0lMNmRp
            RVUxc1psSytzak51RnArV0JxQjBXRlQ5K3dzClhPcmFOVnNjN25MeUlod2NKVWJm
            dFNYK0FvZ0NRSTJHamVUZzVkSFljaGMKLS0tIG5CNmNCc2ZYdko0dlQ1SFFqRzVG
            K0hCUUNXNTdNMVlUS0lGLzhndmp0SUkK6izWJ6X35AI9+z3RMIKRB/R2tdda+O11
            vD9x7/3Wj/WOUubkPeWBwWTUo2vrfwfSSiKl//0cZfdbIKbJj8jUmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T00:04:38Z"
    mac: ENC[AES256_GCM,data:Ym7C/VTtjlFgee9Ht+k4/ISFboGgsN9nzA+wPF5+Qdj2XixxhqGSHRxu1zk9W3YWcI6XXkJ5Bhaju2A2J1CyFQGBoyW9ViP6za/ZF6RzC0vQ9K1E+AdJAhwjzoTBZk+gytlp6vMA0j3/y3Qxq329GVEd8QY/ePsrRNP/FoDYeY0=,iv:jfFgNXg3CkSitxyHFPcKVOSp4Y+LZh6OcHiNUkKqydI=,tag:siIFNBy3/dJ7mY9RiMtBNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|literals)$
    version: 3.8.1
