apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.11.x'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      # Use HostPort for Talos (no LoadBalancer in homelab)
      kind: DaemonSet
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      service:
        type: NodePort
      # Resource limits for homelab
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      # Metrics for monitoring (optional)
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      # Talos: Use host network
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
